# Generated by Django 3.0.5 on 2020-05-04 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webinar', '0002_justuser_just_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='justuser',
            name='just_id',
        ),
    ]
